### ISSUE TITLE
Checklist of fields

### ISSUE THREAD

**Issue by peterdesmet** [riparias/crsenne-occurrences#1]
eee = especes exotique envahissante

- [x] `fulcrum_id`: mapped
- [x] `created_at`: ignore
- [x] `updated_at`: mapped
- [x] `created_by`: ignore (email)
- [x] `updated_by`: ignore (email)
- [x] `system_created_at`: ignore
- [x] `system_updated_at`: ignore
- [x] `version`: ignore
- [ ] `status`:
- [x] `project`: ignore (NA)
- [x] `assigned_to`: ignore (email)
- [x] `latitude`: mapped 
- [x] `longitude`: mapped
- [ ] `geometry`:
- [ ] `statut`:
- [ ] `statut_other`:
- [ ] `observateurs`:
- [ ] `date`: used
- [ ] `cours_d_eau`: mapped
- [ ] `commune`:
- [ ] `commune_other`:
- [ ] `rsu`: river subunit
- [ ] `modules_riparias`: the 3 main survey methods, for which a different set of columns will be populated:
  - cours d'eau et plaine (cep)
  - etang plante aquatiques (aqua)
  - etang ecrevisses (ecrev)

## CEP

- [ ] `unite_spatiale`:
- [ ] `unite_spatiale_other`:
- [ ] `longueur_du_segment`:
- [ ] `eee_riparias_liste_alerte`: EEE observees / Pas d'EEE observees
- [ ] `remarque`:
- [ ] `espece_cep`: species name field, e.g. Impatience glandulifera
- [ ] `espece_cep_other`: species name field, e.g. elodea nutalii
- [ ] `surface_d_occupation`:
- [ ] `indice_abondance`:
- [ ] `nombre_de_pieds`:
- [ ] `population_source`:
- [ ] `population_source_other`:
- [ ] `photos_sp_alerte_cep`:
- [ ] `photos_sp_alerte_cep_caption`:
- [ ] `photos_sp_alerte_cep_url`:
- [ ] `remarque_sp_alerte_ce`:

## aqua

- [ ] `address_aqua_sub_thoroughfare`:
- [ ] `address_aqua_thoroughfare`:
- [ ] `address_aqua_suite`:
- [ ] `address_aqua_locality`:
- [ ] `address_aqua_sub_admin_area`:
- [ ] `address_aqua_admin_area`:
- [ ] `address_aqua_postal_code`:
- [ ] `address_aqua_country`:
- [ ] `address_aqua_full`:
- [ ] `proprietaire_et_coordonnes_aqua`:
- [ ] `envasement_aqua`:
- [ ] `envasement_aqua_other`:
- [ ] `usage_du_site_aqua`:
- [ ] `usage_du_site_aqua_other`:
- [ ] `sp_aqua_indigenes`: species name field, e.g. Ceratophyllum demersum,Lemna minor (et al.)
- [ ] `sp_aqua_indigenes_other`: species name field, e.g. massette, salicaire
- [ ] `remarques_aqua`:
- [ ] `liste_alerte_sp_aqua`: Pas EEE observees / EEE observees
- [ ] `espece_aqua`: species name field, e.g. Pontederia cordata (Alert)
- [ ] `espece_aqua_other`: species name field, e.g. nymphaea sp
- [ ] `surface_d_occupation_aqua`:
- [ ] `indice_abondance_aqua`:
- [ ] `nombre_de_pieds_aqua`:
- [ ] `photos_sp_alerte_aqua`:
- [ ] `photos_sp_alerte_aqua_caption`:
- [ ] `photos_sp_alerte_aqua_url`:
- [ ] `taille_etang`:
- [ ] `acces_machine`:
- [ ] `ensoleillement`:
- [ ] `assec_possible`:
- [ ] `sp_protegees`: SP protegees non observees
- [ ] `nom_sp_protegees`: NA
- [ ] `risque_dispersion_eee`:
- [ ] `risque_dispersion_eee_other`:
- [ ] `explication_du_risque`:
- [ ] `faisabilit`:
- [ ] `mesures`:
- [ ] `resultat_attendu`:
- [ ] `resultat_attendu_other`:
- [ ] `priorite`:
- [ ] `remarque_sp_alerte_aqua`:
- [ ] `arrivee_et_sortie_deau`:
- [ ] `address_ecrev_sub_thoroughfare`:
- [ ] `address_ecrev_thoroughfare`:
- [ ] `address_ecrev_suite`:
- [ ] `address_ecrev_locality`:
- [ ] `address_ecrev_sub_admin_area`:
- [ ] `address_ecrev_admin_area`:
- [ ] `address_ecrev_postal_code`:
- [ ] `address_ecrev_country`:
- [ ] `address_ecrev_full`:
- [ ] `proprietaire_et_coordonnes_ecrev`:
- [ ] `envasement_ecrev`:
- [ ] `envasement_ecrev_other`:
- [ ] `usage_du_site_ecrev`:
- [ ] `usage_du_site_ecrev_other`:
- [ ] `nbr_pieges`:

## ECREV

- [ ] `liste_alerte_sp_ecrev`: Pas ecrev observees / Ecrev observees
- [ ] `sp_ecrevisse`: species name field, but NA
- [ ] `sp_ecrevisse_other`: species name field, e.g. Faxonius limosus
- [ ] `nbr_individu_par_piege`:
- [ ] `remarques_ecrev`:
